version: '3.8'

services:
  app:
    build:
      context: .  # Build context is the current directory
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/public  # Adjust if your structure differs
    networks:
      - app-network

  db:
    image: mysql:5.7
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: intramuros
      MYSQL_ROOT_PASSWORD: yourpassword  # Change to a strong password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
